<?php

return [
    'openapi' => '3.0.0',

    'info' => [
        'title' => env('APP_NAME', 'Laravel API'),
        'description' => 'API Documentation automatically generated by Docs Generate',
        'version' => '1.0.0',
        'contact' => [
            'name' => 'API Support',
            'email' => 'support@example.com',
        ],
    ],

    'servers' => [
        [
            'url' => env('APP_URL', 'http://localhost'),
            'description' => 'API Server',
        ],
    ],

    'security_schemes' => [
        'sanctum' => [
            'type' => 'http',
            'scheme' => 'bearer',
            'bearerFormat' => 'JWT',
            'description' => 'Laravel Sanctum authentication',
        ],
    ],

    'default_security' => [
        ['sanctum' => []],
    ],

    'route_filters' => [
        'prefix' => 'api/',
        'exclude_patterns' => [
            'sanctum/*',
            'telescope/*',
            'horizon/*',
            '_ignition/*',
        ],
    ],

    'http_methods' => [
        'include' => ['GET', 'POST', 'PUT', 'PATCH', 'DELETE'],
        'exclude' => ['HEAD', 'OPTIONS'],
    ],

    'tag_mappings' => [
        'AuthController' => 'Authentication',
        'UserController' => 'Users',
        'ProfileController' => 'Profile',
        'PostController' => 'Posts',
        'CommentController' => 'Comments',
        'ProductController' => 'Products',
        'OrderController' => 'Orders',
        'CategoryController' => 'Categories',
    ],

    'method_summaries' => [
        'index' => 'Get all :resource',
        'store' => 'Create a new :resource',
        'show' => 'Get a specific :resource',
        'update' => 'Update a :resource',
        'destroy' => 'Delete a :resource',
    ],

    'method_descriptions' => [
        'index' => 'Retrieve a list of all :resource with pagination support',
        'store' => 'Create a new :resource with the provided data',
        'show' => 'Retrieve detailed information about a specific :resource',
        'update' => 'Update an existing :resource with new data',
        'destroy' => 'Permanently delete a :resource from the system',
    ],

    'response_codes' => [
        'index' => [200],
        'store' => [201, 422],
        'show' => [200, 404],
        'update' => [200, 404, 422],
        'destroy' => [204, 404],
    ],

    'field_detection' => [
        'email' => [
            'type' => 'string',
            'format' => 'email',
            'example' => 'user@example.com',
        ],
        'password' => [
            'type' => 'string',
            'format' => 'password',
            'example' => 'SecureP@ssw0rd',
            'minLength' => 8,
        ],
        'phone' => [
            'type' => 'string',
            'format' => 'phone',
            'example' => '+1234567890',
        ],
        'url' => [
            'type' => 'string',
            'format' => 'uri',
            'example' => 'https://example.com',
        ],
        'date' => [
            'type' => 'string',
            'format' => 'date',
            'example' => '2025-01-01',
        ],
        'datetime' => [
            'type' => 'string',
            'format' => 'date-time',
            'example' => '2025-01-01T12:00:00Z',
        ],
        'uuid' => [
            'type' => 'string',
            'format' => 'uuid',
            'example' => '550e8400-e29b-41d4-a716-446655440000',
        ],
        'image' => [
            'type' => 'string',
            'format' => 'binary',
            'description' => 'Image file',
        ],
        'file' => [
            'type' => 'string',
            'format' => 'binary',
            'description' => 'File upload',
        ],
    ],

    'validation_rule_mappings' => [
        'string' => 'string',
        'integer' => 'integer',
        'numeric' => 'number',
        'boolean' => 'boolean',
        'array' => 'array',
        'email' => 'string',
        'url' => 'string',
        'date' => 'string',
        'uuid' => 'string',
        'json' => 'object',
    ],

    'output_path' => public_path('api-docs.json'),

    'cors' => [
        'enabled' => true,
        'allow_origins' => [env('APP_URL', 'http://localhost')],
        'allow_methods' => ['GET', 'POST', 'PUT', 'DELETE', 'OPTIONS'],
        'allow_headers' => ['Content-Type', 'Authorization', 'Accept'],
        'allow_credentials' => false,
        'max_age' => 86400,
    ],

    'endpoint_overrides' => [
        'login' => [
            'body' => [
                'email' => 'user@example.com',
                'password' => 'SecurePassword123',
            ],
        ],
        'verifyOtp' => [
            'body' => [
                'user_id' => 1,
                'otp' => '123456',
            ],
        ],
        'register' => [
            'body' => [
                'name' => 'John Doe',
                'email' => 'john@example.com',
                'password' => 'SecurePassword123',
                'phone' => '+1234567890',
            ],
        ],
        'show' => [
            'path' => [
                'id' => 1,
            ],
        ],
        'update' => [
            'path' => [
                'id' => 1,
            ],
            'body' => [
                'name' => 'Updated Name',
            ],
            'headers' => [
                'X-Custom-Header' => 'custom-value',
            ],
        ],
    ],

    'documentation_auth' => [
        'enabled' => env('DOCS_AUTH_ENABLED', false),
        'type' => env('DOCS_AUTH_TYPE', 'none'),
        'allowed_emails' => env('DOCS_AUTH_ALLOWED_EMAILS', ''),
    ],

    'routes' => [
        'enabled' => env('DOCS_ROUTES_ENABLED', true),
        'documentation_path' => env('DOCS_PATH', '/docs'),
        'json_path' => env('DOCS_JSON_PATH', '/docs.json'),
        'middleware' => ['web', 'docs.cors', 'docs.auth'],
    ],
];

